[aes/pre_syn] Added missing files to re-enable Yosys synthesis for AES
The following errors occured during Yosys synthesis:
ERROR: Module `\prim_reg_we_check' referenced in module
`\aes_reg_top' in cell `\u_prim_reg_we_check' is not part
of the design.
ERROR: Module `\prim_onehot_check' referenced in module
`\prim_reg_we_check' in cell `\u_prim_onehot_check' is not part
of the design.

Solution was to add the corresponding files to the Yosys synthesis
script.

Signed-off-by: Moritz Wettermann <moritz.wettermann@gi-de.com>