[dvsim] Add exclude hidden files when needed
Only when hidden files exist, adds `--exclude` option to rsync.

Problem:

    If all hidden files are added into `.gitignore` then rsync error out
    with the message:

    ERROR: [dvsim] Failed to copy over opentitan to scratch/...:
    zsh:1: no matches found: --exclude=.*

Signed-off-by: Eunchan Kim <eunchan@opentitan.org>